server:
  port: 8761

spring:
  application:
    name: server-name

eureka:
  server:
    eviction-interval-timer-in-ms: 10000
    enable-self-preservation: false
  instance:
    hostname: 127.0.0.1
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/