spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ZXAXKL/backserver.git
          search-paths:
          username: ZXAXKL
          password: Zzylovefxy1314