server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ZXAXKL/backServer.git
          username: ZXAXKL
          password: Zzylovefxy1314
          timeout: 5
          force-pull: true
          search-paths: config
      lable: master

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: 127.0.0.1
    instance-id: ${eureka.instance.hostname}:${server.port}
    status-page-url: http://${spring.cloud.client.ip-address}:${server.port}/swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: "*"